source "https://rubygems.org"

gem "sinatra", "~> 1.4"
gem "sinatra-contrib", "~> 1.4"
gem "haml", "~> 4"
gem "suitor", path: "../../core"

group :test do
  gem "rspec", "~> 3.0"
  gem "rack-test"
  gem "capybara", "~> 2.4.1"
  gem "selenium-webdriver"
end
